pluginManagement {
    repositories {
        maven { url 'https://repo.huaweicloud.com/repository/maven' }
        maven { url 'https://repo.huaweicloud.com/repository/maven' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        google()
        mavenCentral()
    }
}

buildscript {
    repositories {
        maven { url 'https://repo.huaweicloud.com/repository/maven' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.50'
    }
}

rootProject.name = "CountdownDay"
include ':app'
