#!/bin/bash
# GitHub Upload Script for CountdownDay

echo "======================================"
echo "CountdownDay - GitHub 上传指南"
echo "======================================"
echo ""
echo "请按以下步骤操作："
echo ""
echo "1️⃣ 首先，确保你已安装 Git"
echo "   在终端运行: git --version"
echo ""
echo "2️⃣ 配置 Git 用户信息（如果还没有）"
echo "   git config --global user.name '你的GitHub用户名'"
echo "   git config --global user.email '你的GitHub邮箱'"
echo ""
echo "3️⃣ 添加所有文件到 Git"
echo "   git add ."
echo ""
echo "4️⃣ 提交代码"
echo "   git commit -m 'Initial commit: 倒数日纪念日应用 v1.0'"
echo ""
echo "5️⃣ 在 GitHub 上创建新仓库"
echo "   - 访问 https://github.com/new"
echo "   - Repository name: CountdownDay"
echo "   - 不要勾选 'Initialize this repository with a README'"
echo "   - 点击 'Create repository'"
echo ""
echo "6️⃣ 复制仓库 URL，然后运行以下命令（将 YOUR_USERNAME 替换为你的用户名）"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/CountdownDay.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "======================================"
echo "或者，如果你有 GitHub Token，可以在这里直接配置："
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/CountdownDay.git"
echo "   git remote set-url origin https://YOUR_TOKEN@github.com/YOUR_USERNAME/CountdownDay.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "======================================"
echo ""
echo "完成后，你的项目就会在 GitHub 上了！🎉"
echo ""

# 显示当前状态
echo "📋 当前 Git 状态："
git status
echo ""
echo "📝 待提交的文件："
git diff --cached --name-only | head -20
